// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"encoding/json"
	"time"
)

type FetchLock struct {
	RepoID    int32     `json:"repo_id"`
	Timeframe string    `json:"timeframe"`
	LockedAt  time.Time `json:"locked_at"`
}

type Repo struct {
	ID          int32     `json:"id"`
	Owner       string    `json:"owner"`
	Name        string    `json:"name"`
	FullName    string    `json:"full_name"`
	Description string    `json:"description"`
	Stars       int32     `json:"stars"`
	Forks       int32     `json:"forks"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Snapshot struct {
	ID        int32           `json:"id"`
	RepoID    int32           `json:"repo_id"`
	Timeframe string          `json:"timeframe"`
	Data      json.RawMessage `json:"data"`
	FetchedAt time.Time       `json:"fetched_at"`
}
