// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package sqlcgen

import (
	"context"
	"encoding/json"
	// "fmt"
	// "time"
	// "fmt"
	// "time"
)

const acquireFetchLock = `-- name: AcquireFetchLock :exec
INSERT INTO fetch_locks (repo_id, timeframe)
VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AcquireFetchLockParams struct {
	RepoID    int32  `json:"repo_id"`
	Timeframe string `json:"timeframe"`
}

func (q *Queries) AcquireFetchLock(ctx context.Context, arg AcquireFetchLockParams) error {
	_, err := q.db.ExecContext(ctx, acquireFetchLock, arg.RepoID, arg.Timeframe)
	return err
}

const getOrCreateRepo = `-- name: GetOrCreateRepo :one
INSERT INTO repos (owner, name, full_name, description, stars, forks)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (full_name) DO UPDATE
    SET description = EXCLUDED.description,
        stars       = EXCLUDED.stars,
        forks       = EXCLUDED.forks,
        updated_at  = now()
RETURNING id, owner, name, full_name, description, stars, forks, created_at, updated_at
`

type GetOrCreateRepoParams struct {
	Owner       string `json:"owner"`
	Name        string `json:"name"`
	FullName    string `json:"full_name"`
	Description string `json:"description"`
	Stars       int32  `json:"stars"`
	Forks       int32  `json:"forks"`
}

func (q *Queries) GetOrCreateRepo(ctx context.Context, arg GetOrCreateRepoParams) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getOrCreateRepo,
		arg.Owner,
		arg.Name,
		arg.FullName,
		arg.Description,
		arg.Stars,
		arg.Forks,
	)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.Description,
		&i.Stars,
		&i.Forks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRepoByFullName = `-- name: GetRepoByFullName :one
SELECT id, owner, name, full_name, description, stars, forks, created_at, updated_at FROM repos WHERE full_name = $1 LIMIT 1
`

func (q *Queries) GetRepoByFullName(ctx context.Context, fullName string) (Repo, error) {
	row := q.db.QueryRowContext(ctx, getRepoByFullName, fullName)
	var i Repo
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.FullName,
		&i.Description,
		&i.Stars,
		&i.Forks,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSnapshot = `-- name: GetSnapshot :one
SELECT id, repo_id, timeframe, data, fetched_at FROM snapshots
WHERE repo_id = $1 AND timeframe = $2
LIMIT 1
`

type GetSnapshotParams struct {
	RepoID    int32  `json:"repo_id"`
	Timeframe string `json:"timeframe"`
}

func (q *Queries) GetSnapshot(ctx context.Context, arg GetSnapshotParams) (Snapshot, error) {
	row := q.db.QueryRowContext(ctx, getSnapshot, arg.RepoID, arg.Timeframe)
	var i Snapshot
	err := row.Scan(
		&i.ID,
		&i.RepoID,
		&i.Timeframe,
		&i.Data,
		&i.FetchedAt,
	)
	return i, err
}

const isFetchLocked = `-- name: IsFetchLocked :one
SELECT EXISTS(
    SELECT 1 FROM fetch_locks
    WHERE repo_id = $1 AND timeframe = $2
      AND locked_at > now() - INTERVAL '5 minutes'
) AS locked
`

type IsFetchLockedParams struct {
	RepoID    int32  `json:"repo_id"`
	Timeframe string `json:"timeframe"`
}

func (q *Queries) IsFetchLocked(ctx context.Context, arg IsFetchLockedParams) (bool, error) {
	row := q.db.QueryRowContext(ctx, isFetchLocked, arg.RepoID, arg.Timeframe)
	var locked bool
	err := row.Scan(&locked)
	return locked, err
}

const releaseFetchLock = `-- name: ReleaseFetchLock :exec
DELETE FROM fetch_locks
WHERE repo_id = $1 AND timeframe = $2
`

type ReleaseFetchLockParams struct {
	RepoID    int32  `json:"repo_id"`
	Timeframe string `json:"timeframe"`
}

func (q *Queries) ReleaseFetchLock(ctx context.Context, arg ReleaseFetchLockParams) error {
	_, err := q.db.ExecContext(ctx, releaseFetchLock, arg.RepoID, arg.Timeframe)
	return err
}

const updateRepo = `-- name: UpdateRepo :exec
UPDATE repos SET description = $2, stars = $3, forks = $4, updated_at = now()
WHERE id = $1
`

type UpdateRepoParams struct {
	ID          int32  `json:"id"`
	Description string `json:"description"`
	Stars       int32  `json:"stars"`
	Forks       int32  `json:"forks"`
}

func (q *Queries) UpdateRepo(ctx context.Context, arg UpdateRepoParams) error {
	_, err := q.db.ExecContext(ctx, updateRepo,
		arg.ID,
		arg.Description,
		arg.Stars,
		arg.Forks,
	)
	return err
}

const upsertSnapshot = `-- name: UpsertSnapshot :exec
INSERT INTO snapshots (repo_id, timeframe, data, fetched_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (repo_id, timeframe) DO UPDATE
    SET data       = EXCLUDED.data,
        fetched_at = now()
`

type UpsertSnapshotParams struct {
	RepoID    int32           `json:"repo_id"`
	Timeframe string          `json:"timeframe"`
	Data      json.RawMessage `json:"data"`
}

func (q *Queries) UpsertSnapshot(ctx context.Context, arg UpsertSnapshotParams) error {
	_, err := q.db.ExecContext(ctx, upsertSnapshot, arg.RepoID, arg.Timeframe, arg.Data)
	return err
}
